### ISSUE TITLE
telegram Can't send messages to non-contacts

### ISSUE THREAD

**Issue by mehran740** [vysheng/tg#776]
Can't send messages to non-contacts
when i send pm to other people not send and say
Method: messages.sendMessage
Result: {"_":"rpc_error","error_code":420,"error_message":"FLOOD_WAIT_86400"}
Stack: Error
    at h (https://web.telegram.org/js/app.js:16:26020)
    at https://web.telegram.org/js/app.js:16:27238
    at l (https://web.telegram.org/js/app.js:8:6393)
    at https://web.telegram.org/js/app.js:8:6565
    at u.$eval (https://web.telegram.org/js/app.js:8:13762)
    at u.$digest (https://web.telegram.org/js/app.js:8:12258)
    at https://web.telegram.org/js/app.js:8:13847
    at s (https://web.telegram.org/js/app.js:7:744)
    at https://web.telegram.org/js/app.js:7:2742
    at n (https://web.telegram.org/js/app.js:2:16525)
what i do????

**Comment by LukeLR** [comment]
Are you sure that your question is about the command line version of telegram? It rather looks like it occured to you on the telegram web client. If so, then you need to head over to https://github.com/zhukov/webogram since this is the repository for the linux command line version.

**Comment by mehran740** [comment]
in web telegram say it and in android not send

**Comment by LukeLR** [comment]
As I already said, that's the wrong place for your question here. This repository is for the Linux command line version of Telegram, other clients have their own GitHub pages. But I'll answer your question now. As always, when there's an error message: Read it. What does it say? This will help you in most cases and you don't need to ask somewhere. In this case, the message has a FLOOD_WAIT-flag attached, which means that you sent too many messages in a given timeframe, and therefore got banned for spamming for exactly 1 day.

**Comment by mehran740** [comment]
im so sorry tnx

**Comment by LukeLR** [comment]
You don't need to feel sorry, but it's better if you ask your questions at the right places.
