### ISSUE TITLE
Unable to sign in to Telegram Chrome app

### ISSUE THREAD

**Issue by marine03tow** [vysheng/tg#900]
Newly installed Telegram Chrome app, going through the sign on screen to the generating keys screen, I repeatedly get an error that I'm "Too fast. You are performing too many actions. Please try again later."

These are the technical details:

Method: auth.sendCode
Result: {"_":"rpc_error","error_code":420,"error_message":"FLOOD_WAIT_86400"}
Stack: Error
    at u (chrome-extension://clhhggbfdinjmjhajaheehoeibfljjno/js/app.js:18:3697)
    at chrome-extension://clhhggbfdinjmjhajaheehoeibfljjno/js/app.js:18:5296
    at l (chrome-extension://clhhggbfdinjmjhajaheehoeibfljjno/js/app.js:8:11738)
    at chrome-extension://clhhggbfdinjmjhajaheehoeibfljjno/js/app.js:8:11910
    at m.$eval (chrome-extension://clhhggbfdinjmjhajaheehoeibfljjno/js/app.js:8:19316)
    at m.$digest (chrome-extension://clhhggbfdinjmjhajaheehoeibfljjno/js/app.js:8:17747)
    at chrome-extension://clhhggbfdinjmjhajaheehoeibfljjno/js/app.js:8:19403
    at a (chrome-extension://clhhggbfdinjmjhajaheehoeibfljjno/js/app.js:7:2845)
    at chrome-extension://clhhggbfdinjmjhajaheehoeibfljjno/js/app.js:7:4299
    at n (chrome-extension://clhhggbfdinjmjhajaheehoeibfljjno/js/app.js:2:17073)

**Comment by beMoD** [comment]
Hi marine03tow,

this is not the Chrome app repository. If you mean https://chrome.google.com/webstore/detail/telegram/clhhggbfdinjmjhajaheehoeibfljjno, then the correct repository would be https://github.com/zhukov/webogram
